### ISSUE TITLE
Licenses

### ISSUE THREAD

**Issue by misterhat** [SimonLarsen/safetyblanket#1]
Can you add licenses for the files and assets here? 

From what the website says, all of the source code here is zlib, except for slam.lua. slam.lua doesn't state it, but it looks like the MIT/X11 license. I also noticed AnAL.lua wasn't listed in the exceptions and it's also written by a different author. It appears to be under the MIT/Expat license.

The graphics and sounds are covered under CC-BY-SA-4.0.

The font is apparently written by a Japanese author under what may be a non-commercial clause (if somebody could translate this accurately, it would be appreciated):

> <<< 著作権など >>>
> 
> 当サイトのフォント、及び画像はフリーウエアですが、著作権を放棄したものではありません。
> HP等に個人で使用する事は構いませんが、作者の許可なく販売したり、
> 営利目的の製品に添付する事は固く禁じさせて頂きます。
> ## また、フォントを使用してのいかなる損害についても作者は責任を負わないものとします。
> 
> copyright(c)2001-2002 BitmapMania All right reserved.
> http://bitmapmania.m78.com/
> cooz@m78.com

FYI: I'm in the process of packaging this for Debian.

**Comment by SimonLarsen** [comment]
Hi. Sorry for the sloppiness regarding licenses.

I just got contacted the author of slam to get some kind of license from him. 
I'll try to figure something out with the font. Might have to replace it. I would like to avoid having an NC-clause on any of the assets.

I'll get back to you soon.

**Comment by SimonLarsen** [comment]
Took me forever to find a free licensed replacement font but everything should be in order now.
- BM Germar has been replaced with CC-BY licensed replacement
- Module TSerial.lua has been replaced with my own library
- Modules slam.lua and AnAL.lua are both MIT license
- Added LICENSE.txt file declaring these things

**Comment by misterhat** [comment]
Awesome, thank you! Once it's released I'll prepare prepare the updated package.

**Comment by SimonLarsen** [comment]
New release: https://github.com/SimonLarsen/safetyblanket/releases/tag/v1.01
